name: gemhog

services:
  postgres:
    image: postgres:18
    container_name: gemhog-postgres
    environment:
      POSTGRES_DB: gemhog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - gemhog_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  gemhog_postgres_data:
